Fix error for workflows

diff --git a/.github/workflows/build_packages.yaml b/.github/workflows/build_packages.yaml
--- a/.github/workflows/build_packages.yaml
+++ b/.github/workflows/build_packages.yaml
@@ -28,26 +28,17 @@ jobs:
             
         steps:
         - uses: actions/checkout@v1
-        - name: set aws
-          run: |
-            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-            aws2 configure set aws_access_key_id ${{ secrets.AwsAccessKeyId }} 
-            aws2 configure set aws_secret_access_key ${{ secrets.AwsSecretAccessKey }} 
-            aws2 configure set default.region us-west-2
         - name: build emqx packages
           env:
             ERL_OTP: erl22.1
             SYSTEM: ${{ matrix.os }}
           run: |
-            version=$(echo ${{ github.ref }} | sed -r  "s .*/.*/(.*) \1 g")
             docker run -i --name emqtt-$SYSTEM-build -v $(pwd):/emqtt emqx/build-env:$ERL_OTP-$SYSTEM /bin/bash -c "make -C /emqtt pkg"
             cd _packages && for var in $(ls); do sudo bash -c "echo $(sha256sum $var | awk '{print $1}') > $var.sha256"; done && cd -
-            aws2 s3 cp --recursive ./_packages  s3://packages.emqx.io/emqtt/$version
-        - name: upload
-          if: github.event_name == 'release'
-          run: |
+        - uses: actions/upload-artifact@v1
+          with:
+            name: packages-${{ matrix.os }}
+            path: _packages/.
             
     build-on-mac:
         runs-on: macos-latest
@@ -63,24 +54,18 @@ jobs:
           run: |
             curl -Lo /usr/local/bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
             chmod +x /usr/local/bin/rebar3
-        - name: set aws
-          run: |
-            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-macos.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-            aws2 configure set aws_access_key_id ${{ secrets.AwsAccessKeyId }} 
-            aws2 configure set aws_secret_access_key ${{ secrets.AwsSecretAccessKey }} 
-            aws2 configure set default.region us-west-2
         - name: build
           run: |
             make emqtt
             mkdir -p _packages
-            version=$(echo ${{ github.ref }} | gsed -r  "s .*/.*/(.*) \1 g")
-            pkg=emqtt-macos-$version.zip
+            pkg=emqtt-macos-$(git describe --tags --always).zip
             cd _build/emqtt/rel && zip -rq $pkg emqtt && cd -
             mv _build/emqtt/rel/$pkg _packages/
             openssl dgst -sha256 ./_packages/$pkg | awk '{print $2}' > ./_packages/$pkg.sha256
-            aws2 s3 cp --recursive ./_packages  s3://packages.emqx.io/emqtt/$version
+        - uses: actions/upload-artifact@v1
+          with:
+            name: packages-mac
+            path: _packages/.
 
     release:
         runs-on: ubuntu-latest
@@ -89,6 +74,46 @@ jobs:
         
         steps:
         - uses: actions/checkout@v2
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-ubuntu18.04
+            path: _packages
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-ubuntu16.04
+            path: _packages
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-ubuntu14.04
+            path: _packages
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-debian10
+            path: _packages
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-debian9
+            path: _packages
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-debian8
+            path: _packages
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-opensuse
+            path: _packages
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-centos7
+            path: _packages
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-centos6
+            path: _packages
+        - uses: actions/download-artifact@v1
+          with:
+            name: packages-mac
+            path: _packages
         - name: set aws
           run: |
             curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
@@ -99,10 +124,14 @@ jobs:
             aws2 configure set default.region us-west-2
         - name: get packages
           run: |
-            mkdir -p _packages
+            cd _packages && for var in $( ls |grep emqtt |grep -v sha256); do 
+              echo "$(cat $var.sha256) $var" | sha256sum -c || echo "$var check sha256 error" && exit 1
+            done
+        - name: upload aws
+          run: |
             version=$(echo ${{ github.ref }} | sed -r  "s .*/.*/(.*) \1 g")
-            aws2 s3 cp --recursive s3://packages.emqx.io/emqtt/$version ./_packages
-            cd _packages && for var in $( ls |grep emqtt |grep -v sha256); do echo "$(cat $var.sha256) $var" | sha256sum -c || echo "$var check sha256 error" && exit 1 ;done
+            aws2 s3 cp --recursive ./_packages  s3://packages.emqx.io/emqtt/$version
+            aws2 cloudfront create-invalidation --distribution-id E3TYD0WSP4S14P --paths "/emqtt/$version/*"
         - name: upload github
           if: github.event_name == 'release'
           run: |
